//
// Created by roboy on 03.04.20.
//
////////////////////////////////////////////////////////////////////////////////
// Copyright 2019 FZI Research Center for Information Technology
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
// this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation
// and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its
// contributors may be used to endorse or promote products derived from this
// software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////
#include <ros/ros.h>

// ros_control
#include <realtime_tools/realtime_buffer.h>
#include <realtime_tools/realtime_box.h>

class PDController {
public:
    PDController() {};
    PDController(const PDController& other){
        // The autogenerated copy constructor
        // calls m_gains(other.m_gains), which binds a non-const reference to const.
        m_gains = other.m_gains;

        // Shallow copy of m_dyn_conf_server is fine
    }
    ~PDController() {}

    void init(std::vector<double> g){

        m_gains.initRT(PDGains(g[0],g[1]));
    // Connect dynamic reconfigure and overwrite the default values with values
    // on the parameter server. This is done automatically if parameters with
    // the according names exist.
//    m_callback_type = boost::bind(
//            &PDController::dynamicReconfigureCallback, this, _1, _2);
//
//    m_dyn_conf_server.reset(
//    new dynamic_reconfigure::Server<PDGainsConfig>(
//    ros::NodeHandle(name_space)));
//    m_dyn_conf_server->setCallback(m_callback_type);

}

    double operator()(const double& error, const ros::Duration& period){
        if (period == ros::Duration(0.0))
        {
            return 0.0;
        }

        PDGains gains(*m_gains.readFromRT());
        double result = gains.m_p * error + gains.m_d * (error - m_last_p_error) / period.toSec();

        m_last_p_error = error;
        return result;
    }

private:
    struct PDGains
    {
        PDGains()
                : m_p(1), m_d(1)
        {};

        PDGains(double p, double d)
                : m_p(p), m_d(d)
        {};

        double m_p; ///< proportional gain
        double m_d; ///< derivative gain
    };

    realtime_tools::RealtimeBuffer<PDGains> m_gains;

    double m_last_p_error;

    // Dynamic reconfigure
//    typedef cartesian_controller_base::PDGainsConfig PDGainsConfig;
//    void dynamicReconfigureCallback(PDGainsConfig& config, uint32_t level);

//    boost::shared_ptr<dynamic_reconfigure::Server<PDGainsConfig> > m_dyn_conf_server;
//    dynamic_reconfigure::Server<PDGainsConfig>::CallbackType m_callback_type;

};